variables:
  repo_dir_install: ./install/
  host_dir_install: /bitrix/bitrix-docker/www/bitrix/modules/p10102022.p10102022paycode2022/install
  repo_dir_lang: ./lang/
  host_dir_lang: /bitrix/bitrix-docker/www/bitrix/modules/p10102022.p10102022paycode2022/lang
  host_dir_pay: /bitrix/bitrix-docker/www/bitrix/modules/p10102022.p10102022paycode2022

stages:
  - deploy

deploy-stage:
  stage: deploy
  only: 
    - bitrix
  tags:
    - bitrix
  script:
    - sudo rsync --remove-source-files -r ${repo_dir_install} ${host_dir_install}
    - sudo rsync --remove-source-files -r ${repo_dir_lang} ${host_dir_lang}
    - sudo chown -R www-data:www-data ${host_dir_pay}